### ISSUE TITLE
Website Feedback

### ISSUE THREAD

**Issue by samtaggart** [freeflownation/www_earthproject#1]
I think it's quite good overall and tells a nice story. :) If you agree with these changes, I can make them @Vilnite.

I do think we can make the call to action stronger – part of that is addressed here and part of that will take a conversation.

- [x] I would add a Support Button to the top navigation which leads to the Support block on the page. Also I would add TAG x ThreeFold in the menu bar as well.

- [x] There is a typo on the first sentence of the page – eduction >>> education.

- [x] I think Take Action Global needs more context since it hasn't been introduced yet to the visitor. I would say something like: EarthProject is created by Take Action Global, a community of teachers worldwide that connects with refugee camps to increase the level of quality education locally and fight polarization globally.

- [x] "Our Journey So Far" I might turn into "The TAG Journey So Far."

- [x] Under 2015, April Kakuma Project, remove "a" before 325 teachers.

- [x] Under 2017, October Climate Action, it says "We united all teachers" ... is this all teachers in the world? in the community?

- [x] Under 2019, January INNOVATION LAB SCHOOL, the first sentence says "we involved our own global goals book" but how was it involved? It's not clear. "We involved our own global goals book to _____." Also there is no period at the end of the second sentence.

- [x] Under TAG x THREEFOLD it says "We Take Action Global to the next level" I kind of like it, but is it intentional? Should it be "We take Take Action Global..." In the next sentence it should be "further than" and "equal chances" or "an equal chance" instead of just "equal chance."

- [x] Down below in the "As one world" section, it says "Earth Project" but should it be "EarthProject" ?

- [x] The "Support" button doesn't go anywhere

- [x] Under "Supported By a Global Community" I would make the pictures clickable with references / news articles, if possible. Otherwise we just say supported, without any backing.

**Comment by Vilnite** [comment]
Fantastic, thank you for your feedback @samtaggart 
Let's get on a call, go through all together and implement these changes.

We also are looking into having EarthProject as a use case for alltogether.land let's keep that in mind so we can update site accordingly when ready.

**Comment by samtaggart** [comment]
Hi @vilnite I made most of the changes and pushed them to development. We can talk about it on the call.

One thing I realized is that we still have PlanEd on the wiki so I pointed the Support button to the TDE wiki section but we're going to need to rectify that before we push this site live.

At any rate, we'll jump on the phone.

**Comment by Vilnite** [comment]
Wiki needs update for sure. Will tackle that, thank you.
